language: node_js
node_js:
  - "4.1"

language: ruby
rvm:
  - "2.1"

env:
  - DISPLAY=:99.0
  
before_install:
  - sh -e /etc/init.d/xvfb start
  - npm install selenium-webdriver
  - gem install jekyll
  - jekyll build
  
  
install: gem install html-proofer
script: 
  - htmlproof ./_site --verbose true --file_ignore node_modules, tests