language: node_js
node_js:
  - "4.1"

language: ruby
rvm:
  - "2.1"

env:
#  - DISPLAY=:99.0
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
before_install:
#  - sh -e /etc/init.d/xvfb start
#  - npm install selenium-webdriver
  - gem install jekyll
  - jekyll build
  
  
install: gem install html-proofer
script: 
  - htmlproof ./_site --verbose --disable-external --file-ignore './_site/node_modules/*'