language: node_js
node_js:
  - "4.1"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
#  - galen check galen-test/home.gspec --url http://localhost:4000/ --size 1024x768 --htmlreport galen-test/reports
  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
  - ./node_modules/karma/bin/karma start my.conf.js

cache:
  directories:
    - node_modules
    - bundler

notifications:
    email: false

before_install:
  - rvm install 2.1.5
  - gem install jekyll
  - gem install html-proofer
  - npm install -g galenframework-cli
